from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import Dict, Any
import io

class DocxService:
    def generate_report(self, data: Dict[str, Any]) -> bytes:
        """
        Generate a Word document compliance report.
        """
        doc = Document()
        
        # Title
        title = doc.add_heading('AI Compliance Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Company Info
        doc.add_heading(f"Analysis for: {data.get('company_name', 'Unknown')}", level=1)
        doc.add_paragraph(f"Score: {data.get('score', 0)}/100")

        # Status
        status_para = doc.add_paragraph()
        status_run = status_para.add_run(f"Status: {data.get('status', 'UNKNOWN')}")
        status_run.bold = True
        if data.get('score', 0) >= 80:
            status_run.font.color.rgb = RGBColor(0, 128, 0) # Green
        else:
            status_run.font.color.rgb = RGBColor(255, 0, 0) # Red

        # Critical Issues
        if data.get('critical_issues'):
            doc.add_heading('Critical Issues (Must Fix)', level=2)
            for issue in data['critical_issues']:
                p = doc.add_paragraph(style='List Bullet')
                run = p.add_run(f"[{issue.get('rule_id')}] {issue.get('description')}")
                run.bold = True
                p.add_run(f"\nRecommendation: {issue.get('recommendation')}")

        # Recommendations
        if data.get('recommendations'):
            doc.add_heading('Recommendations', level=2)
            for rec in data['recommendations']:
                doc.add_paragraph(rec, style='List Bullet')
                
        # Footer
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "Generated by AI Compliance Agent"
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save to Bytes
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream.getvalue()
