from docx import Document
from docx.shared import Pt, RGBColor, Inches, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT
from typing import Dict, Any, List
import io


STATUS_LABELS = {
    "pass": "✅ Pass",
    "fail": "❌ Fail",
    "warning": "⚠️ Warning",
    "info": "ℹ️ Info",
}

STATUS_COLORS = {
    "pass": RGBColor(0, 128, 0),
    "fail": RGBColor(200, 0, 0),
    "warning": RGBColor(200, 150, 0),
    "info": RGBColor(100, 100, 100),
}


class DocxService:
    def generate_report(self, data: Dict[str, Any]) -> bytes:
        """Generate a Word document compliance report in checklist format."""
        doc = Document()

        # Set default font
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(10)

        # Title
        title = doc.add_heading("AI Compliance Report", 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Company & Score
        doc.add_heading(f"Analysis for: {data.get('company_name', 'Unknown')}", level=1)

        # Score & Status
        score = data.get("score", 0)
        status = data.get("status", "UNKNOWN")
        p = doc.add_paragraph()
        run = p.add_run(f"Score: {score}/100  |  Status: {status}")
        run.bold = True
        run.font.size = Pt(14)
        if score >= 80:
            run.font.color.rgb = RGBColor(0, 128, 0)
        elif score >= 50:
            run.font.color.rgb = RGBColor(200, 150, 0)
        else:
            run.font.color.rgb = RGBColor(200, 0, 0)

        # Summary
        summary = data.get("summary", "")
        if summary:
            p = doc.add_paragraph()
            p.add_run(summary).italic = True

        # Generated at
        generated = data.get("generated_at", "")
        if generated:
            p = doc.add_paragraph()
            run = p.add_run(f"Generated: {generated}")
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(128, 128, 128)

        doc.add_paragraph()  # spacer

        # Checklist sections
        checklist = data.get("checklist", [])
        if checklist:
            self._add_checklist_tables(doc, checklist)
        else:
            doc.add_paragraph("No checklist data available.")

        # Footer
        section = doc.sections[0]
        footer = section.footer
        p = footer.paragraphs[0]
        p.text = "Generated by AI Compliance Agent | ECOMMBX Checklist"
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Save to bytes
        file_stream = io.BytesIO()
        doc.save(file_stream)
        file_stream.seek(0)
        return file_stream.getvalue()

    def _add_checklist_tables(self, doc, checklist: List[Dict[str, Any]]):
        """Group checklist items by section and create a table for each."""
        # Group by section
        sections = {}
        for item in checklist:
            sec = item.get("section", "Other")
            if sec not in sections:
                sections[sec] = []
            sections[sec].append(item)

        for section_name, items in sections.items():
            # Section heading
            doc.add_heading(section_name, level=2)

            # Count pass/fail for section summary
            scorable = [i for i in items if i.get("status") in ("pass", "fail", "warning")]
            passed = sum(1 for i in scorable if i.get("status") == "pass")
            total = len(scorable)
            if total > 0:
                p = doc.add_paragraph()
                run = p.add_run(f"Result: {passed}/{total} passed")
                run.bold = True
                run.font.size = Pt(9)
                if passed == total:
                    run.font.color.rgb = RGBColor(0, 128, 0)
                elif passed >= total / 2:
                    run.font.color.rgb = RGBColor(200, 150, 0)
                else:
                    run.font.color.rgb = RGBColor(200, 0, 0)

            # Table
            table = doc.add_table(rows=1, cols=5)
            table.style = "Light Grid Accent 1"
            table.alignment = WD_TABLE_ALIGNMENT.CENTER

            # Header row
            hdr = table.rows[0].cells
            headers = ["#", "Check Item", "Status", "Found", "Recommendation"]
            for i, text in enumerate(headers):
                hdr[i].text = text
                for paragraph in hdr[i].paragraphs:
                    for run in paragraph.runs:
                        run.bold = True
                        run.font.size = Pt(9)

            # Data rows
            for idx, item in enumerate(items, 1):
                row = table.add_row().cells
                status = item.get("status", "info")

                row[0].text = str(idx)
                row[1].text = item.get("item", "")
                row[2].text = STATUS_LABELS.get(status, status)
                row[3].text = self._truncate(item.get("found_value", ""), 80)
                row[4].text = item.get("recommendation", "") or "—"

                # Style the cells
                for cell in row:
                    for paragraph in cell.paragraphs:
                        for run in paragraph.runs:
                            run.font.size = Pt(9)

                # Color the status cell
                for paragraph in row[2].paragraphs:
                    for run in paragraph.runs:
                        color = STATUS_COLORS.get(status)
                        if color:
                            run.font.color.rgb = color
                        run.bold = True

            # Set column widths
            for row in table.rows:
                row.cells[0].width = Cm(1)
                row.cells[1].width = Cm(5)
                row.cells[2].width = Cm(2.5)
                row.cells[3].width = Cm(4)
                row.cells[4].width = Cm(5)

            doc.add_paragraph()  # spacer between sections

    @staticmethod
    def _truncate(text: str, max_len: int) -> str:
        if not text:
            return ""
        return text[:max_len] + "..." if len(text) > max_len else text
